export default{
    icons:[
        {name:"attach", groupName:"Ionicons"},
        {name:"basketball", groupName:"Ionicons"},
        {name:"bicycle", groupName:"Ionicons"},
        {name:"briefcase", groupName:"Ionicons"},
        {name:"contacts", groupName:"Ionicons"},
        {name:"restaurant", groupName:"Ionicons"},
        {name:"heart", groupName:"Ionicons"},
        {name:"medkit", groupName:"Ionicons"},
        {name:"paw", groupName:"Ionicons"},
        {name:"money", groupName:"FontAwesome"},
        {name:"star", groupName:"FontAwesome"},
        {name:"flag", groupName:"FontAwesome"},
        {name:"book", groupName:"FontAwesome"},
        {name:"photo", groupName:"FontAwesome"},
        {name:"gift", groupName:"FontAwesome"},
        {name:"leaf", groupName:"FontAwesome"},
        {name:"key", groupName:"FontAwesome"},
        {name:"wrench", groupName:"FontAwesome"},
        {name:"flask", groupName:"FontAwesome"},
        {name:"umbrella", groupName:"FontAwesome"},
        {name:"gamepad", groupName:"FontAwesome"},
        {name:"airplane", groupName:"MaterialCommunityIcons"},
        {name:"baby-buggy", groupName:"MaterialCommunityIcons"},
        {name:"bank", groupName:"MaterialCommunityIcons"},
        {name:"brush", groupName:"MaterialCommunityIcons"},
        {name:"bottle-wine", groupName:"MaterialCommunityIcons"},
        {name:"pill", groupName:"MaterialCommunityIcons"},
        {name:"bus-side", groupName:"MaterialCommunityIcons"},
        {name:"cake", groupName:"MaterialCommunityIcons"},
        {name:"cart", groupName:"MaterialCommunityIcons"},
        {name:"gas-station", groupName:"MaterialCommunityIcons"},
    ]
}