export default{
    icons:[
        {id:1, name:"attach", groupName:""},
        {id:2, name:"basketball", groupName:""},
        {id:3, name:"bicycle", groupName:""},
        {id:4, name:"briefcase", groupName:""},
        {id:5, name:"contacts", groupName:""},
        {id:6, name:"fitness", groupName:""},
        {id:7, name:"heart", groupName:""},
        {id:8, name:"medkit", groupName:""},
        {id:9, name:"paw", groupName:""},
        {id:10, name:"star", groupName:"FontAwesome"},
        {id:11, name:"flag", groupName:"FontAwesome"},
        {id:12, name:"book", groupName:"FontAwesome"},
        {id:13, name:"photo", groupName:"FontAwesome"},
        {id:14, name:"gift", groupName:"FontAwesome"},
        {id:15, name:"leaf", groupName:"FontAwesome"},
        {id:16, name:"key", groupName:"FontAwesome"},
        {id:17, name:"wrench", groupName:"FontAwesome"},
        {id:18, name:"flask", groupName:"FontAwesome"},
        {id:19, name:"umbrella", groupName:"FontAwesome"},
        {id:20, name:"gamepad", groupName:"FontAwesome"},
        {id:21, name:"airplane", groupName:"MaterialCommunityIcons"},
        {id:22, name:"baby-buggy", groupName:"MaterialCommunityIcons"},
        {id:23, name:"bank", groupName:"MaterialCommunityIcons"},
        {id:24, name:"blender", groupName:"MaterialCommunityIcons"},
        {id:25, name:"bottle-wine", groupName:"MaterialCommunityIcons"},
        {id:26, name:"brush", groupName:"MaterialCommunityIcons"},
        {id:27, name:"bus-side", groupName:"MaterialCommunityIcons"},
        {id:28, name:"cake", groupName:"MaterialCommunityIcons"},
        {id:29, name:"cart", groupName:"MaterialCommunityIcons"},
        {id:30, name:"doctor", groupName:"MaterialCommunityIcons"},
    ]
}